apiVersion: v1
kind: Service
metadata:
  name: website-cloth-service
  namespace: default
spec:
  selector:
    app: website-cloth
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021
